service: fedeira-personal-services
frameworkVersion: '4'
variablesResolutionMode: 20210326

# AWS provider configuration:
provider:
  name: aws
  runtime: nodejs18.x
  profile: Developer-Fedeira
  region: us-east-2
  stage: dev
  apiName: 'dev-fedeira-personal-services'
  deploymentBucket:
    name: dev-fedeira-personal-services-bucket
  apiGateway:
    minimumCompressionSize: 1024
  tags:
    Project: 'Fedeira Personal Services'
    Service: 'Personal-services'
    Environment: 'dev'

  environment:
    IS_OFFLINE: 'false'

    # SSM
    ACCOUNT_NUMBER_PPI: ${env:ACCOUNT_NUMBER_PPI, ssm:/fedeira-personal-services/ppi/accountNumber}
    AUTHORIZED_CLIENT_PPI: ${env:AUTHORIZED_CLIENT_PPI, ssm:/fedeira-personal-services/ppi/authorizedClient}

    CLIENT_KEY_PPI_PROD: ${env:CLIENT_KEY_PPI_PROD, ssm:/fedeira-personal-services/prod/ppi/clientKey}
    API_KEY_PPI_PROD: ${env:API_KEY_PPI_PROD, ssm:/fedeira-personal-services/prod/ppi/apiKey}
    API_SECRET_PPI_PROD: ${env:API_SECRET_PPI_PROD, ssm:/fedeira-personal-services/prod/ppi/apiSecret}

    JWT_SECRET: ${env:JWT_SECRET, ssm:/fedeira-personal-services/auth/jwt/secret}
    USER_EMAIL: ${env:USER_EMAIL, ssm:/fedeira-personal-services/user/email}
    USER_PASSWORD: ${env:USER_PASSWORD, ssm:/fedeira-personal-services/user/password}

    ENCRYPTION_KEY: ${env:ENCRYPTION_KEY, ssm:/fedeira-personal-services/crypto/encryptionKey}

    # ENV locales
    API_VERSION_PPI: ${env:API_VERSION_PPI}
    API_KEY_PPI_TEST: ${env:API_KEY_PPI_TEST}
    API_SECRET_PPI_TEST: ${env:API_SECRET_PPI_TEST}
    CLIENT_KEY_PPI_TEST: ${env:CLIENT_KEY_PPI_TEST}
    ACCOUNT_NUMBER_PPI_TEST: ${env:ACCOUNT_NUMBER_PPI}
    AUTHORIZED_CLIENT_PPI_TEST: ${env:AUTHORIZED_CLIENT_PPI}
    BASE_URL_PPI_TEST: ${env:BASE_URL_PPI_TEST}
    BASE_URL_PPI_PROD: ${env:BASE_URL_PPI_PROD}
    ENCRYPTION_ALGORITHM: ${env:ENCRYPTION_ALGORITHM, 'aes-256-cbc'}
    ENCRYPTION_RANDOM_BYTES: ${env:ENCRYPTION_RANDOM_BYTES, '16'}
    USER_EMAIL_TEST: ${env:USER_EMAIL}
    USER_PASSWORD_TEST: ${env:USER_PASSWORD}

  # Monitoring & Logging:
  tracing:
    apiGateway: true
    lambda: true
  logs:
    restApi: true
    logRetentionInDays: 30

  # IAM role permissions for Lambda functions:
  iam:
    role:
      statements:
        # Permit for ssm operations
        - Effect: 'Allow'
          Action:
            - 'ssm:GetParameter'
            - 'ssm:GetParameters'
          Resource:
            - !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/fedeira-personal-services/*'
        # Permit for dynamodb operations
        - Effect: 'Allow'
          Action:
            - 'dynamodb:Query'
            - 'dynamodb:Scan'
            - 'dynamodb:GetItem'
            - 'dynamodb:PutItem'
            - 'dynamodb:UpdateItem'
            - 'dynamodb:DeleteItem'
          Resource:
            - !Sub 'arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/UserCredentials'
            - !Sub 'arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/Accounts'
        # Permit for logs operations in cloudwatch
        - Effect: 'Allow'
          Action:
            - 'logs:CreateLogGroup'
            - 'logs:CreateLogStream'
            - 'logs:PutLogEvents'
          Resource: !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/*'
        # Permit for ses operations
        - Effect: 'Allow'
          Action:
            - 'ses:SendEmail'
            - 'ses:SendRawEmail'
          Resource: '*'
        # Permit for S3 operations
        - Effect: 'Allow'
          Action:
            - 's3:ListBucket'
            - 's3:GetBucketLocation'
            - 's3:GetObject'
            - 's3:PutObject'
          Resource:
            - 'arn:aws:s3:::dev-fedeira-personal-services-bucket'
            - 'arn:aws:s3:::dev-fedeira-personal-services-bucket/*'
# Lambda functions definitions:
functions:
  # Custom authorizer Lambda for API Gateway (verifies JWT tokens)
  auth-service-authorizer:
    handler: authorization-services/handler.authorizer
    name: 'dev-fedeira-authorization-services-authorizer'
    memorySize: 1024
    timeout: 10
  #  Authorizer lambda: Lambda for authorization-related endpoints
  authorization-service:
    handler: authorization-services/handler.login
    name: 'dev-fedeira-authorization-services'
    timeout: 29
    memorySize: 1024
    events:
      - http:
          path: login
          method: post
          cors: true
  # Investment domain Lambda:
  investment-service:
    handler: investment-services/handler.getAvailableBalance
    name: 'dev-fedeira-investment-services'
    timeout: 29
    memorySize: 1024
    events:
      - http:
          path: investment/available-balance
          method: get
          cors: true
          authorizer:
            name: auth-service-authorizer
            type: TOKEN
  # Account domain Lambda:
  account-service:
    handler: account-services/handler.getAccounts
    name: 'dev-fedeira-account-services'
    timeout: 29
    memorySize: 1024
    events:
      - http:
          path: accounts
          method: get
          cors: true
          authorizer:
            name: auth-service-authorizer
            type: TOKEN
  # Reports domain Lambda:
  reports-service:
    handler: reports-services/lambda.handler
    name: 'dev-fedeira-reports-services'
    runtime: nodejs18.x
    timeout: 29
    memorySize: 1024
    events:
      - http:
          path: reports
          method: post
          cors: true
          authorizer:
            name: auth-service-authorizer
            type: TOKEN

# AWS Resources: DynamoDB Table & S3 Bucket:
resources:
  Resources:
    UserCredentialsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: UserCredentials
        AttributeDefinitions:
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: email
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
    AccountsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Accounts
        AttributeDefinitions:
          - AttributeName: account
            AttributeType: S
          - AttributeName: user
            AttributeType: S
        KeySchema:
          - AttributeName: account
            KeyType: HASH
          - AttributeName: user
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST

    # API Gateway access logs:
    ApiGatewayAccessLogs:
      Type: AWS::Logs::LogGroup
      Properties:
        LogGroupName:
          Fn::Sub: 'API-Gateway-Execution-Logs_${ApiGatewayRestApi}/dev'
        RetentionInDays: 30
