service: fedeira-personal-services
frameworkVersion: '4'
useDotenv: true

# Serverless plugins:
plugins:
  - serverless-esbuild
  - serverless-dynamodb-local
  - serverless-offline
  - serverless-secrets-plugin

# AWS provider configuration:
provider:
  name: aws
  runtime: nodejs18.x
  profile: Fedeira-Developer
  region: us-east-2
  apiName: "${opt:stage, 'dev'}-fedeira-personal-services"
  deploymentBucket:
    name: fedeira-personal-services-bucket
  apiGateway:
    minimumCompressionSize: 1024
    binaryMediaTypes:
      - 'application/json'
  # Tags for better resource management in AWS:
  tags:
    Project: 'Fedeira Personal Services'
    Service: 'Personal-services'
    Environment: "${opt:stage, 'dev'}"
  # Environment variables available for Lambda functions:
  environment:
    IS_OFFLINE: ${opt:isOffline, 'false'}

    # SSM
    ACCOUNT_NUMBER_PPI: ${env:ACCOUNT_NUMBER_PPI, ${ssm:/fedeira-personal-services/ppi/accountNumber}}
    AUTHORIZED_CLIENT_PPI: ${env:AUTHORIZED_CLIENT_PPI, ${ssm:/fedeira-personal-services/ppi/authorizedClient}}

    CLIENT_KEY_PPI_PROD: ${env:CLIENT_KEY_PPI_PROD, ${ssm:/fedeira-personal-services/prod/ppi/clientKey~true}}
    API_KEY_PPI_PROD: ${env:API_KEY_PPI_PROD, ${ssm:/fedeira-personal-services/prod/ppi/apiKey~true}}
    API_SECRET_PPI_PROD: ${env:API_SECRET_PPI_PROD, ${ssm:/fedeira-personal-services/prod/ppi/apiSecret~true}}

    JWT_SECRET: ${env:JWT_SECRET, ${ssm:/fedeira-personal-services/auth/jwt/secret~true}}
    USER_EMAIL: ${env:USER_EMAIL, ${ssm:/fedeira-personal-services/user/email}}
    USER_PASSWORD: ${env:USER_PASSWORD, ${ssm:/fedeira-personal-services/user/password~true}}

    ENCRYPTION_KEY: ${env:ENCRYPTION_KEY, ${ssm:/fedeira-personal-services/crypto/encryptionKey~true}}
    # ENV
    API_VERSION_PPI: ${env:API_VERSION_PPI}
    API_KEY_PPI_TEST: ${env:API_KEY_PPI_TEST}
    API_SECRET_PPI_TEST: ${env:API_SECRET_PPI_TEST}
    CLIENT_KEY_PPI_TEST: ${env:CLIENT_KEY_PPI_TEST}
    ACCOUNT_NUMBER_PPI_TEST: ${env:ACCOUNT_NUMBER_PPI}
    AUTHORIZED_CLIENT_PPI_TEST: ${env:AUTHORIZED_CLIENT_PPI}
    BASE_URL_PPI_TEST: ${env:BASE_URL_PPI_TEST}
    BASE_URL_PPI_PROD: ${env:BASE_URL_PPI_PROD}
    ENCRYPTION_ALGORITHM: ${env:ENCRYPTION_ALGORITHM, 'aes-256-cbc'}
    ENCRYPTION_RANDOM_BYTES: ${env:ENCRYPTION_RANDOM_BYTES, '16'}
    USER_EMAIL_TEST: ${env:USER_EMAIL}
    USER_PASSWORD_TEST: ${env:USER_PASSWORD}

  # Monitoring & Logging:
  tracing:
    apiGateway: true
    lambda: true
  logs:
    restApi: true

  # IAM role permissions for Lambda functions:
  iam:
    role:
      statements:
        # Permit for ssm operations
        - Effect: 'Allow'
          Action:
            - 'ssm:GetParameter'
          Resource:
            - 'arn:aws:ssm:${self:provider.region}:${self:custom.accountId}:parameter/fedeira-personal-services/*'
        # Permit for dynamodb operations
        - Effect: 'Allow'
          Action:
            - 'dynamodb:Query'
            - 'dynamodb:Scan'
            - 'dynamodb:GetItem'
            - 'dynamodb:PutItem'
            - 'dynamodb:UpdateItem'
            - 'dynamodb:DeleteItem'
          Resource:
            - 'arn:aws:dynamodb:${self:provider.region}:${self:custom.accountId}:table/UserCredentials'
            - 'arn:aws:dynamodb:${self:provider.region}:${self:custom.accountId}:table/Accounts'
        # Permit for logs operations in cloudwatch
        - Effect: 'Allow'
          Action:
            - 'logs:CreateLogGroup'
            - 'logs:CreateLogStream'
            - 'logs:PutLogEvents'
          Resource: 'arn:aws:logs:${self:provider.region}:${self:custom.accountId}:log-group:/aws/lambda/*'
        # Permit for ses operations
        - Effect: 'Allow'
          Action:
            - 'ses:SendEmail'
            - 'ses:SendRawEmail'
          Resource: 'arn:aws:ses:${self:provider.region}:${self:custom.accountId}:identity/my-secure-domain.com'
        # Permit for S3 operations
        - Effect: 'Allow'
          Action:
            - 's3:CreateBucket'
            - 's3:DeleteBucket'
            - 's3:ListBucket'
            - 's3:GetBucketLocation'
            - 's3:GetObject'
            - 's3:PutObject'
          Resource:
            - 'arn:aws:s3:::fedeira-personal-services-bucket'
            - 'arn:aws:s3:::fedeira-personal-services-bucket/*'
# Lambda functions definitions:
functions:
  # Custom authorizer Lambda for API Gateway (verifies JWT tokens)
  authServiceAuthorizer:
    handler: authorization-services/handler.authorizer
    name: "${opt:stage, 'dev'}-fedeira-authorization-services-authorizer"
    memorySize: 1024
    timeout: 10
  #  Authorizer lambda: Lambda for authorization-related endpoints
  authorizationService:
    handler: authorization-services/handler.login
    name: "${opt:stage, 'dev'}-fedeira-authorization-services"
    timeout: 29
    memorySize: 1024
    events:
      - http:
          path: login
          method: post
          cors: true
          authorizer: none
  # Investment domain Lambda:
  investmentService:
    handler: investment-services/handler.getAvailableBalance
    name: "${opt:stage, 'dev'}-fedeira-investment-services"
    timeout: 29
    memorySize: 1024
    events:
      - http:
          path: investment/available-balance
          method: get
          cors: true
          authorizer:
            name: authServiceAuthorizer
            type: TOKEN
  # Account domain Lambda:
  accountService:
    handler: account-services/handler.getAccounts
    name: "${opt:stage, 'dev'}-fedeira-account-services"
    timeout: 29
    memorySize: 1024
    events:
      - http:
          path: accounts
          method: get
          cors: true
          authorizer:
            name: authServiceAuthorizer
            type: TOKEN

# AWS Resources: DynamoDB Table & S3 Bucket:
resources:
  Resources:
    UserCredentialsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: UserCredentials
        AttributeDefinitions:
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: email
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
    AccountsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Accounts
        AttributeDefinitions:
          - AttributeName: account
            AttributeType: S
          - AttributeName: user
            AttributeType: S
        KeySchema:
          - AttributeName: account
            KeyType: HASH
          - AttributeName: user
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST

    # Bucket creation
    PersonalServicesBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: fedeira-personal-services-bucket
        PublicAccessBlockConfiguration:
          BlockPublicAcls: true
          BlockPublicPolicy: true
          IgnorePublicAcls: true
          RestrictPublicBuckets: true
        BucketEncryption:
          ServerSideEncryptionConfiguration:
            - ServerSideEncryptionByDefault:
                SSEAlgorithm: AES256

  Outputs:
    DynamoDBEndpoint:
      Description: DynamoDB Local Endpoint (for offline reference)
      Value: 'http://localhost:8000'

# Custom configurations:
custom:
  accountId: ${env:AWS_ACCOUNT_ID}

  esbuild:
    bundle: true
    minify: false
    sourcemap: false
    target: node18
    platform: node
    exclude: ['aws-sdk']
  secrets:
    parameters:
      '/ppi/token': '{"token":"mi-token-prueba","expiration":1700000000000,"refreshToken":"mi-refresh"}'

  # DynamoDB local settings for offline development:
  dynamodb:
    stages: [dev]
    start:
      port: 8000
      inMemory: true
      seed: true
      convertEmptyValues: true

  # Packaging settings:
  package:
    individually: true
    include:
      - common/**
      - authorization-services/**
      - investment-services/**
      - account-services/**
      - node_modules/**
      - dist/**
